name: "James Kitchens"
job_title: "Environmental Data Scientist & Creative Programmer"

social_links: 
  - {name: GitHub, icon: "fab fa-github", link: "https://github.com/kitchensjn"}
  - {name: LinkedIn, icon: "fab fa-linkedin", link: "https://www.linkedin.com/in/james-kitchens-668825b2/"}
  - {name: CV, icon: "fas fa-file-alt", link: "/assets/CV/KitchensJames_CV.pdf"}

location: "Pomona, California"
email: "kitchensjn@gmail.com"
phone: "(804) 572-3197"

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true